sudo: false


# Enable C++ support
language: cpp


## Install dependencies
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5


matrix:
  include:
    # Compiler selection
    - compiler: gcc


script:
  - export CXX=g++-5
  - export CC=gcc-5
  - cd ../
  - root=`pwd`

  # Install boost
  - boost_major=1
  - boost_minor=58
  - boost_patch=0
  - version=${boost_major}.${boost_minor}.${boost_patch}
  - boost=boost_${boost_major}_${boost_minor}_${boost_patch}
  - wget http://downloads.sourceforge.net/project/boost/boost/${version}/${boost}.tar.bz2
  - tar xf ${boost}.tar.bz2
  - cd ${boost}
  - ./bootstrap.sh
  - ./b2 install -d+0 --link=shared --prefix=${root}/boost --with-system --with-program_options
  - cd ../

  # Build Club
  - cd gnunet_channels
  - mkdir build
  - cd build
  - cmake .. -DBOOST_INCLUDEDIR=${root}/boost/include -DBOOST_LIBRARYDIR=${root}/boost/lib
  - make
