version: 2
executorType: machine

stages:
  build:
    environment:
      - CMAKE_PATH: "/home/circleci/cmake-3.10.0-Linux-x86_64/bin"

    steps:
      - type: checkout

      - type: shell
        name: Install cmake
        command: |
          cd ~
          wget --quiet https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz
          tar -xf cmake-3.10.0-Linux-x86_64.tar.gz

      - type: shell
        name: Install other dependencies
        command: |
          sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install g++-5 autopoint libtool libunistring-dev libsqlite3-dev libgcrypt20-dev libidn11-dev zlib1g-dev texinfo

      - type: shell
        name: Install Boost
        command: |
          cd ~
          boost_major=1
          boost_minor=58
          boost_patch=0
          boost=boost_${boost_major}_${boost_minor}_${boost_patch}
          wget http://downloads.sourceforge.net/project/boost/boost/${boost_major}.${boost_minor}.${boost_patch}/${boost}.tar.bz2
          tar xf ${boost}.tar.bz2
          cd ${boost}
          ./bootstrap.sh
          ./b2 install -j `nproc` -d+0 --link=shared --prefix=${HOME}/boost --with-system --with-program_options --with-test --with-coroutine

      - type: shell
        name: Build
        command: |
          git submodule sync --recursive
          git submodule update --recursive --init
          mkdir build
          cd build
          export CXX=g++-5
          export CC=gcc-5
          export PATH="$CMAKE_PATH:$PATH"
          cmake .. -DBOOST_INCLUDEDIR=~/boost/include -DBOOST_LIBRARYDIR=~/boost/lib
          make

      - type: shell
        name: Run tests
        command: |
          repo=`pwd`
          root=$repo/build/gnunet
          cd build

          cfg1=$repo/scripts/peer1.conf
          cfg2=$repo/scripts/peer2.conf

          mkdir -p $repo/scripts/gnunet1
          mkdir -p $repo/scripts/gnunet2

          export LD_LIBRARY_PATH=$root/lib:~/boost/lib:$LD_LIBRARY_PATH
          export PATH=$root/bin:$PATH
          
          export GNUNET_TEST_HOME=$repo/scripts

          gnunet-arm -s -c $cfg1 &
          gnunet-arm -s -c $cfg2 &

          sleep 3

          echo "Showing peerinfo"
          gnunet-peerinfo -s -c $cfg1
          gnunet-peerinfo -s -c $cfg2

          echo "Interconnecting the two peers"
          gnunet-peerinfo -c $cfg2 -p `gnunet-peerinfo -c $cfg1 -g` &

          sleep 5

          ./tests --log_level=test_suite
